### ISSUE TITLE
Can't delete last digit in some formats

### ISSUE THREAD

**Issue by yume-chan** [jorisre/react-telephone#179]
1. Open the official demo https://react-telephone.joris.re/
2. Select "United States" in the country dropdown
3. Type "1" into the number input box
4. Press Backspace

Actual result:

Nothing happens.

Browser: Microsoft Edge:	103.0.1264.37 (Official build) (64-bit)

**Comment by jorisre** [comment]
Good catch! fixed in #392 sorry for the delay
